POST http://127.0.0.1:8000/login
Content-Type: application/json

{ "username": "laravel", "password": "Pass1234!" }

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{ "username": "laravel", "password": "Pass1234!", "email": "lara@gmail.com" }

###
GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 124e1cfeb662ba0a8692ddf8f6bbd8336b78b4a3

{  }